# List of organization units
organization_units:
  <organization unit name>: # organization unit name where to deploy products
    # list of the AWS Service Catalog products
    products:
      - product_name: <product name> # name of the product
        product_version: <(optional) product version # optional value. If omitted the latest version of product will be deployed
        portfolio_name: <portfolio name> # name of the portfolio 
        provision_name: <product provision name> # name use by AWS Service Catalog to provision product 
        dependson: # optional: list of the provision names that must to be deployed before product
          - <provision name dependency>
        parameters: # optional: list of parameters and values
          - Key: <parameter key name>
            Value: <parameter key value>
        regions: # list of AWS regions where to deploy product
          - <aws region>
  # products listed under default OU will be deploy to every new account
  default:
    # list of the AWS Service Catalog products
    products:
      - product_name: <product name> # name of the product
        product_version: <(optional) product version # optional value. If omitted the latest version of product will be deployed
        portfolio_name: <portfolio name> # name of the portfolio 
        provision_name: <product provision name> # name use by AWS Service Catalog to provision product 
        dependson: # optional: list of the provision names that have to be deploy before product
          - <provision name dependency>
        parameters: # optional: list of parameters and values
          - Key: <parameter key name>
            Value: <parameter key value>
        regions: # list of AWS regions where to deploy product
          - <aws region>
# optional: overwrite default value for maximum iteration 
max_iterations: <number of iterations>
