# * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# *
# * Permission is hereby granted, free of charge, to any person obtaining a copy of this
# * software and associated documentation files (the "Software"), to deal in the Software
# * without restriction, including without limitation the rights to use, copy, modify,
# * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# * permit persons to whom the Software is furnished to do so.
# *
# * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AWSTemplateFormatVersion: 2010-09-09
Description: Service Catalog DMS Replication Instance Product
Parameters:
  ReplicationInstanceIdentifier:
    Description: Replication Instance Name
    Type: String
  ReplicationInstanceClass:
    Description: Replication Instance Type
    Type: String
  Storage:
      Type: Number
      MinValue: 50
      MaxValue: 500
      Default: 50
      Description: Allocate Storage in GB min 50 max 500
  KMSId:
    Description: KMS Encryption Key Id
    Type: String
  EngineVersion:
    Description: Engine Version
    Type: String
  ReplicationSubnetGroupIdentifier:
    Description: Replication Subnet Group Identifier
    Type: String
  SecurityGroupIds:
    Description: VPC Security Groups Ids
    Type: CommaDelimitedList
  Tags:
    Description: The tags to be applied to the resource.
    Type: String
    Default: ''

Conditions:
  HasTags: !Not [!Equals [!Ref Tags, '']]

Resources:
  GetTags:
    Type: "Custom::ResourceCompliance"
    Condition : HasTags
    Version: "1.0"
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:sc-resource-compliance'
      Action:
        Name: json
        Parameters:
          JSON: !Ref Tags
          Type: Tags
  ReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      AllocatedStorage: !Ref Storage
      AutoMinorVersionUpgrade: False
      EngineVersion: !Ref EngineVersion
      KmsKeyId: !Ref KMSId
      MultiAZ: False
      PubliclyAccessible: False
      ReplicationInstanceClass: !Ref ReplicationInstanceClass
      ReplicationInstanceIdentifier: !Ref ReplicationInstanceIdentifier
      ReplicationSubnetGroupIdentifier: !Ref ReplicationSubnetGroupIdentifier
      Tags: !If [HasTags, !GetAtt GetTags.Json, !Ref "AWS::NoValue"]
      VpcSecurityGroupIds: !Ref SecurityGroupIds

Outputs:
  ReplicationInstance:
    Value: !Ref ReplicationInstance
    Export:
      Name: !Sub ${AWS::StackName}-ReplicationInstance
