# * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# *
# * Permission is hereby granted, free of charge, to any person obtaining a copy of this
# * software and associated documentation files (the "Software"), to deal in the Software
# * without restriction, including without limitation the rights to use, copy, modify,
# * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# * permit persons to whom the Software is furnished to do so.
# *
# * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AWSTemplateFormatVersion: 2010-09-09
Description: Service Catalog DMS Endpoint Product
Parameters:
  EndpointIdentifier:
    Description: Endpoint Name
    Type: String
  EndpointType:
    Description: Endpoint Type
    Type: String
    Default: source
    AllowedValues:
      - source
      - target
  EngineName:
    Description: Engine Name
    Type: String
  DatabaseName:
    Description: Database Name
    Type: String
  ServerName:
    Description: Server Name
    Type: String
  Port:
    Description: Port
    Type: Number
    Default: 1521
  UserName:
    Description: User Name
    Type: String
  Password:
    Description: Password
    Type: String
    NoEcho: True
  KMSId:
    Description: KMS Encryption Key Id
    Type: String
  Tags:
    Description: The tags to be applied to the resource.
    Type: String
    Default: ''
    
Conditions:
  HasTags: !Not [!Equals [!Ref Tags, '']]

Resources:
  GetTags:
    Type: "Custom::ResourceCompliance"
    Condition : HasTags
    Version: "1.0"
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:sc-resource-compliance'
      Action:
        Name: json
        Parameters:
          JSON: !Ref Tags
          Type: Tags
  Endpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      DatabaseName: !Ref DatabaseName
      EndpointIdentifier: !Ref EndpointIdentifier
      EndpointType: !Ref EndpointType
      EngineName: !Ref EngineName
      KmsKeyId: !Ref KMSId
      Password: !Ref Password
      Username: !Ref UserName
      Port: !Ref Port
      ServerName: !Ref ServerName
      SslMode: none
      Tags: !If [HasTags, !GetAtt GetTags.Json, !Ref "AWS::NoValue"]

Outputs:
  Endpoint:
    Value: !Ref Endpoint
    Export:
      Name: !Sub ${AWS::StackName}-Endpoint
