# * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# *
# * Permission is hereby granted, free of charge, to any person obtaining a copy of this
# * software and associated documentation files (the "Software"), to deal in the Software
# * without restriction, including without limitation the rights to use, copy, modify,
# * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# * permit persons to whom the Software is furnished to do so.
# *
# * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AWSTemplateFormatVersion: 2010-09-09
Description: Provision ElastiCache from Service Catalog
Parameters:
  ClusterName:
    Description: Cluster Name
    Type: String
  NodeType:
    Description: Elasticache Node Type
    Type: String
  NumberClusters:
    Description: Number of Cache Clusters
    Type: Number
    MinValue: 1
    MaxValue: 6
    Default: 2
    ConstraintDescription: Value must be between 1-6
  AuthToken:
    Description: The password that's used to access a password-protected server
    Type: String
    NoEcho: true
  CacheSubnetGroupName:
    Description: Cache Subnet Group Name
    Type: String
  SecurityGroupIds:
    Description: Security Groups Ids
    Type: String
  ProvisionedApplicationName:
    Description: 'Name of Provision Application'
    Type: String

Resources:
  ProductSelector:
    Type: "Custom::ProductSelector"
    Version: "1.0"
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:sc-product-selector'
      Action:
        Name: product
        Parameters:
          ProductName: elasticache
  EC:
    Type: "AWS::ServiceCatalog::CloudFormationProvisionedProduct"
    Properties:
      ProvisionedProductName: !Ref ProvisionedApplicationName
      ProvisioningParameters:
        - Key: ClusterName
          Value: !Ref ClusterName
        - Key: NodeType
          Value: !Ref NodeType
        - Key: NumberClusters
          Value: !Ref NumberClusters
        - Key: AuthToken
          Value: !Ref AuthToken
        - Key: CacheSubnetGroupName
          Value: !Ref CacheSubnetGroupName
        - Key: SecurityGroupIds
          Value: !Ref SecurityGroupIds

      ProductId: !GetAtt ProductSelector.ProductId
      ProvisioningArtifactId: !GetAtt ProductSelector.ArtifactId

Outputs:
  ProductTemplateName:
    Value: !Select [1, !Split ['/', !Select [5, !Split [':', !GetAtt EC.CloudformationStackArn ]]]]
