# * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# *
# * Permission is hereby granted, free of charge, to any person obtaining a copy of this
# * software and associated documentation files (the "Software"), to deal in the Software
# * without restriction, including without limitation the rights to use, copy, modify,
# * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# * permit persons to whom the Software is furnished to do so.
# *
# * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AWSTemplateFormatVersion: 2010-09-09
Description: Provision Elasticsearch from Service Catalog
Parameters:
  DomainName:
    Description: User defined Elasticsearch Domain name
    Type: String
  ElasticsearchVersion:
    Description: User defined Elasticsearch Version
    Type: String
    Default: '6.2'
  InstanceType:
    Type: String
  InstanceCount:
      Type: Number
      MinValue: 1
      MaxValue: 3
      Default: 1
  DedicatedMasterType:
    Type: String
    Description: Elastic Search Master Instance Type
  DedicatedMasterCount:
      Type: Number
      MinValue: 0
      MaxValue: 3
      Default: 0
  VolumeSize:
    Description: 'EBS Volume Size'
    Type: Number
    MinValue: 10
    MaxValue: 100
    Default: 10
  EnableZoneAwareness:
    Description: 'Enable ES zone awareness'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  ESAccessPrincipalFull:
    Description: 'Elastic Search Full Access Policy Principal'
    Type: String
    Default: '*'
  ESAccessPrincipalReadOnly:
    Description: 'Elastic Search ReadOnly Access Policy Principal'
    Type: String
    Default: 'None'
  KMSId:
    Description: KMS Encryption Key Id
    Type: String
  SubnetIds:
    Description: VPC Subnets Ids
    Type: String
  SecurityGroupIds:
    Description: VPC Security Groups Ids
    Type: String
  ProvisionedApplicationName:
    Description: 'Name of Provision Application'
    Type: String

Resources:
  ProductSelector:
    Type: "Custom::ProductSelector"
    Version: "1.0"
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:sc-product-selector'
      ProductName: elasticsearch
  ES:
    Type: "AWS::ServiceCatalog::CloudFormationProvisionedProduct"
    Properties:
      ProvisionedProductName: !Ref ProvisionedApplicationName
      ProvisioningParameters:
        - Key: DomainName
          Value: !Ref DomainName
        - Key: ElasticsearchVersion
          Value: !Ref ElasticsearchVersion
        - Key: InstanceType
          Value: !Ref InstanceType
        - Key: InstanceCount
          Value: !Ref InstanceCount
        - Key: DedicatedMasterType
          Value: !Ref DedicatedMasterType
        - Key: DedicatedMasterCount
          Value: !Ref DedicatedMasterCount
        - Key: VolumeSize
          Value: !Ref VolumeSize
        - Key: EnableZoneAwareness
          Value: !Ref EnableZoneAwareness
        - Key: ESAccessPrincipalFull
          Value: !Ref ESAccessPrincipalFull
        - Key: ESAccessPrincipalReadOnly
          Value: !Ref ESAccessPrincipalReadOnly
        - Key: KMSId
          Value: !Ref KMSId
        - Key: SubnetIds
          Value: !Ref SubnetIds
        - Key: SecurityGroupIds
          Value: !Ref SecurityGroupIds
        - Key: Tags
          Value: !Sub 'Name=${DomainName},Environment=Test'           

      ProductId: !GetAtt ProductSelector.ProductId
      ProvisioningArtifactId: !GetAtt ProductSelector.ArtifactId

Outputs:
  ProductTemplateName:
    Value: !Select [1, !Split ['/', !Select [5, !Split [':', !GetAtt ES.CloudformationStackArn ]]]]
